//red
    if (varient =0)
    {
        init_hp=15;
        hp=15;
        damage_type_1=2;
        damage_1=8;
        damage_type_2=5;
        damage_2=2;
        wind_up=3;
        range=3;
        wind_down=2;
        mouvement_speed=1;
        slash_resistence=1.25;
        pierce_resistence=1;
        fire_resistance=0.25;
        ice_resistance=1.25;
        poison_resistance=1.25;
        push_resistance=1.25;
        sprite_index=spr_wizard_red;
        attack_type=1;
        alive=1;
        infected=0;
    }
    //red dead
    if (varient =1)
    {
        init_hp=20;
        hp=20;
        damage_type_1=5;
        damage_1=4;
        damage_type_2=2;
        damage_2=1;
        wind_up=2;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.75;
        pierce_resistence=0.75;
        fire_resistance=0.5;
        ice_resistance=2;
        poison_resistance=0;
        push_resistance=0.75;
        sprite_index=spr_wizard_red_zombie;
        alive=0;
        infected=1;
        attack_type=2;
    }
    //blue 
    if (varient =2)
    {
        init_hp=15;
        hp=15;
        damage_type_1=3;
        damage_1=8;
        damage_type_2=5;
        damage_2=2;
        wind_up=3;
        range=3;
        wind_down=2;
        mouvement_speed=1;
        slash_resistence=1.25;
        pierce_resistence=1;
        fire_resistance=1.25;
        ice_resistance=0.25;
        poison_resistance=1.25;
        push_resistance=1.25;
        sprite_index=spr_wizard_blue;
        attack_type=1;
        alive=1;
        infected=0;
    }
    //blue dead
    if (varient =3)
    {
        init_hp=20;
        hp=20;
        damage_type_1=5;
        damage_1=4;
        damage_type_2=3;
        damage_2=1;
        wind_up=2;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.75;
        pierce_resistence=0.75;
        fire_resistance=2;
        ice_resistance=0.5;
        poison_resistance=0;
        push_resistance=0.75;
        sprite_index=spr_wizard_blue_zombie;
        alive=0;
        infected=1;
        attack_type=2;
    }
     //green
     if (varient =4)
    {
        init_hp=15;
        hp=15;
        damage_type_1=4;
        damage_1=8;
        damage_type_2=5;
        damage_2=2;
        wind_up=3;
        range=3;
        wind_down=2;
        mouvement_speed=1;
        slash_resistence=1.25;
        pierce_resistence=1;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=0.25;
        push_resistance=1.25;
        sprite_index=spr_wizard_green;
        alive=1;
        infected=0;
        attack_type=1;
    }
    //green dead
    if (varient =5)
    {
        init_hp=20;
        hp=20;
        damage_type_1=5;
        damage_1=4;
        damage_type_2=3;
        damage_2=1;
        wind_up=2;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.75;
        pierce_resistence=0.75;
        fire_resistance=1.25;
        ice_resistance=1.25;
        poison_resistance=0;
        push_resistance=0.75;
        sprite_index=spr_wizard_green_zombie;
        alive=0;
        infected=1;
        attack_type=2;
    }
