//shelled
    if (varient =0)
    {
        init_hp=15;
        hp=15;
        damage_type_1=0;
        damage_1=5;
        damage_type_2=0;
        damage_2=0;
        wind_up=1;
        range=1;
        wind_down=2;
        mouvement_speed=1;
        slash_resistence=0.25;
        pierce_resistence=0.25;
        fire_resistance=0.5;
        ice_resistance=0.5;
        poison_resistance=1;
        push_resistance=0.25;
        sprite_index=spr_crab_sheld;
        attack_type=2;
    }
    //unshelled
    if (varient =1)
    {
        damage_type_1=0;
        damage_1=5;
        damage_type_2=0;
        damage_2=0;
        wind_up=1;
        range=1;
        wind_down=2;
        mouvement_speed=1;
        slash_resistence=1;
        pierce_resistence=1;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=1;
        push_resistance=1;
        sprite_index=spr_crab_unsheld;
        attack_type=2;
    }
   
