 if (varient =0)
    {
        init_hp=300;
        hp=300;
        damage_type_1=2;
        damage_1=3;
        damage_type_2=5;
        damage_2=1.1;
        wind_up=7;
        range=5;
        wind_down=1;
        mouvement_speed=1;
        slash_resistence=1.25;
        pierce_resistence=1;
        fire_resistance=1.25;
        ice_resistance=1.25;
        poison_resistance=0.25;
        push_resistance=1;
        attack_type=1;
        alive=0;
        infected=0;
        scr_determin_player_wait_wait_array();
    }
     if (varient =1)
    {
        init_hp=250;
        hp=250;
        damage_type_1=1;
        damage_1=5;
        damage_type_2=0;
        damage_2=0;
        wind_up=7;
        range=5;
        wind_down=1;
        mouvement_speed=1;
        slash_resistence=1.25;
        pierce_resistence=1;
        fire_resistance=1.25;
        ice_resistance=1.25;
        poison_resistance=0.25;
        push_resistance=1.25;
        attack_type=1;
        alive=0;
        infected=0;
        scr_determin_player_wait_wait_array();
    }
