if (varient =0)
    {
        init_hp=10;
        hp=10;
        damage_type_1=5;
        damage_1=2;
        damage_type_2=0;
        damage_2=0;
        wind_up=1;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.5;
        pierce_resistence=1;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=1;
        push_resistance=0.5;
        sprite_index=spr_blob_classic;
        attack_type=2;
    }

    if (varient =1)
    {
        init_hp=10;
        hp=10;
        damage_type_1=2;
        damage_1=4;
        damage_type_2=0;
        damage_2=0;
        wind_up=1;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.5;
        pierce_resistence=1;
        fire_resistance=0;
        ice_resistance=2;
        poison_resistance=1;
        push_resistance=0.5;
        sprite_index=spr_blob_fire;
        attack_type=2;
    }

    if (varient =2)
    {
        init_hp=10;
        hp=10;
        damage_type_1=3;
        damage_1=4;
        damage_type_2=0;
        damage_2=0;
        wind_up=1;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.5;
        pierce_resistence=1;
        fire_resistance=2;
        ice_resistance=0;
        poison_resistance=1;
        push_resistance=0.5;
        sprite_index=spr_blob_ice;
        attack_type=2;
    }

    if (varient =3)
    {
        init_hp=10;
        hp=10;
        damage_type_1=4;
        damage_1=5;
        damage_type_2=0;
        damage_2=0;
        wind_up=3;
        range=2;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.5;
        pierce_resistence=1;
        sprite_index=spr_blob_poison;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=0;
        push_resistance=0.5;
        attack_type=1;
    }
     if (varient =4)
    {
        init_hp=40;
        hp=40;
        damage_type_1=5;
        damage_1=8;
        damage_type_2=4;
        damage_2=2;
        wind_up=2;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.25;
        pierce_resistence=0.75;
        sprite_index=spr_blob_zombie;
        fire_resistance=2;
        ice_resistance=2;
        poison_resistance=0;
        push_resistance=0.5;
        alive=0;
        infected=1;
        attack_type=2;
    }
