//basic
    if (varient =0)
    {
        init_hp=30;
        hp=30;
        damage_type_1=5;
        damage_1=4;
        damage_type_2=4;
        damage_2=1;
        wind_up=1;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.5;
        pierce_resistence=0.5;
        fire_resistance=2;
        ice_resistance=2;
        poison_resistance=0;
        push_resistance=1;
        sprite_index=spr_zombie_classic;
        attack_type=2;
    }
    //halved
    if (varient =1)
    {
        init_hp=15;
        hp=15;
        wind_up=1;
        damage_type_1=5;
        damage_1=4;
        damage_type_2=4;
        damage_2=1;
        range=1;
        wind_down=2;
        mouvement_speed=0.5;
        slash_resistence=0.5;
        pierce_resistence=1.5;
        fire_resistance=2;
        ice_resistance=2;
        poison_resistance=0;
        push_resistance=1;
        sprite_index=spr_zombie_halved;
        attack_type=2;
    }
    //gutted
    if (varient =2)
    {
        init_hp=20;
        hp=20;
        damage_type_1=5;
        damage_1=5;
        damage_type_2=4;
        damage_2=1;
        wind_up=2;
        range=2;
        wind_down=1;
        mouvement_speed=0.5;
        slash_resistence=1.75;
        pierce_resistence=0.5;
        fire_resistance=1.25;
        ice_resistance=1.25;
        poison_resistance=0;
        push_resistance=1.5;
        sprite_index=spr_zombie_gutted;
        attack_type=1;
    }
    //bloater
    if (varient =3)
    {
        init_hp=45;
        hp=45;
        damage_type_1=4;
        damage_1=7;
        damage_type_2=5;
        damage_2=3;
        wind_up=3;
        range=2;
        wind_down=1;
        mouvement_speed=0.5;
        slash_resistence=0.5;
        pierce_resistence=0.7;
        fire_resistance=2.25;
        ice_resistance=2.25;
        poison_resistance=0;
        push_resistance=1;
        sprite_index=spr_zombie_bloater;
        attack_type=1;
    }
