//basic
    if (varient =0)
    {
        init_hp=5;
        hp=5;
        damage_type_1=5;
        damage_1=3;
        damage_type_2=0;
        damage_2=0;
        wind_up=1;
        range=1;
        wind_down=1;
        mouvement_speed=1;
        slash_resistence=1;
        pierce_resistence=0.5;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=0;
        push_resistance=1.5;
        sprite_index=spr_skeleton_classic;
        attack_type=2;
    }
    //soldier
    if (varient =1)
    {
        init_hp=10;
        hp=10;
        wind_up=2;
        damage_type_1=1;
        damage_1=5;
        damage_type_2=0;
        damage_2=0;
        range=1;
        wind_down=2;
        mouvement_speed=1;
        slash_resistence=1;
        pierce_resistence=0.5;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=0;
        push_resistance=1.5;
        sprite_index=spr_skeleton_warrior;
        attack_type=0;
    }
    //archer
    if (varient =2)
    {
        init_hp=5;
        hp=5;
        damage_type_1=0;
        damage_1=5;
        damage_type_2=0;
        damage_2=0;
        wind_up=2;
        range=2;
        wind_down=1;
        mouvement_speed=1;
        slash_resistence=1;
        pierce_resistence=0.5;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=0;
        push_resistance=1.5;
        sprite_index=spr_skeleton_archer;
        attack_type=1;
    }
