//general
    if (varient =0)
    {
        init_hp=15;
        hp=15;
        damage_type_1=0;
        damage_1=2;
        damage_type_2=0;
        damage_2=0;
        wind_up=4;
        range=2;
        wind_down=2;
        mouvement_speed=1;
        slash_resistence=1;
        pierce_resistence=1;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=1;
        push_resistance=1;
        sprite_index=spr_general;
        attack_type=0;
        alive=1;
        infected=0;
    }
    //soldier
    if (varient =1)
    {
        init_hp=20;
        hp=20;
        wind_up=3;
        damage_type_1=2;
        damage_1=1.1;
        damage_type_2=0;
        damage_2=0;
        range=2;
        wind_down=3;
        mouvement_speed=1;
        slash_resistence=1;
        pierce_resistence=1;
        fire_resistance=1;
        ice_resistance=1;
        poison_resistance=1;
        push_resistance=1;
        sprite_index=spr_army_blocking;
        attack_type=0;
        alive=1;
        infected=0;
        
    }
    
