shop_top.selected_item_damage_1=argument0.damage_1;
shop_top.selected_item_damage_type_1=argument0.damage_type_1;
shop_top.selected_item_damage_2=argument0.damage_2;
shop_top.selected_item_damage_type_2=argument0.damage_type_2;
shop_top.selected_item_range=argument0.range;
shop_top.selected_item_AP_use=argument0.AP_use;
shop_top.selected_item_description=argument0.description;
